version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - lambda
    environment:
      - FLASK_ENV=development

  lambda:
    build:
      context: ./lambda
    environment:
      - AWS_REGION=us-east-1

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8080:8080"
    depends_on:
      - api

  log_generator:
    build:
      context: ./scripts
    command: python log_generator.py
    depends_on:
      - lambda

networks:
  default:
    driver: bridge